name:                hephaestus-assets
version:             0.1.0.0
github:              "thi4go/hephaestus-assets"
license:             BSD3
author:              "Thiago Figueiredo"
maintainer:          "thiagofigueiredo777@gmail.com"
copyright:           "CC"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Combinator Library

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thi4go/hephaestus-assets#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hephaestus-assets-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hephaestus-assets

tests:
  hephaestus-assets-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hephaestus-assets
